Hb 1
RuslanIbIsh/movietickets pull request #1
Opened 2021-01-26 22:04 UTC by RuslanIbIsh

2021-01-26 23:01 UTC, Ilya-brinchuk commented on pom.xml
>  </project>
Should be empty line

2021-01-26 23:03 UTC, Ilya-brinchuk approved these changes

2021-01-27 06:56 UTC, RuslanIbIsh commented on pom.xml
>  </project>
done

2021-01-27 08:15 UTC, Sofasmile requested changes

2021-01-27 08:15 UTC, Sofasmile commented on src/main/java/com/iri/movietickets/dao/impl/MovieDaoImpl.java
> +            session.close();
let's add check for `null` value

2021-01-27 08:24 UTC, RuslanIbIsh commented on src/main/java/com/iri/movietickets/dao/impl/MovieDaoImpl.java
> +            session.close();
done

2021-01-27 10:56 UTC, RomanDubovskyi approved these changes

2021-02-01 12:34 UTC, merged